apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-rs
  template:
    metadata:
      labels:
        app: nginx-rs
    spec:
      containers:
      - name: nginx-rs
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rs-svc
spec:
  selector:
    app: nginx-rs
  ports:
  - port: 80
    targetPort: 80

